name: CI

on: [push]

jobs:
  terrafrom:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
      
      - name: Terraform Init
        working-directory: env/dev
        run: terraform init

      - name: formatting terraform code
        working-directory: env/dev
        run: terraform fmt -check
        
      - name: checking the code
        working-directory: env/dev
        run: terraform validate